package com.events;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

class FiltersLists {
    static final List<String> BAD_WORDS_TO_END_ON = Util.list("during", "and", "for", "gives");
    static final List<String> START_QUOTES = Util.list("'", "‘", "\"");
    static final List<String> obscenities = Util.list("fuck", "sh!t-faced", "cunt", "fucking");
    static final List<String> REVERSE_ORDER = Util.list("literature", "comedy", "talk", "concerts", "exhibition", "poetry", "art", "culture", "cabaret", "discussion", "lecture", "panel discussion", "films", "performances", "performance", "show", "gig", "in conversation", "masterclass");
    static final List<String> REVERSE_ORDER_SHORT = Util.list("live", "screening", "concert", "film screening", "film");
    static final List<String> REPEAT_PHRASES_ALLOWED = Util.list("goo", "la");
    static final ArrayList<String> EXC = Util.list("members'", "members only", "member only", "invitation only", "short course", "intermediate course", "one day course", "this course", "week course", "relaxed screening", "meetup group", "teachmeet", "postgraduate study", "carol service", "postgraduate course", "freshers event", "undergraduate study", "tuneless choir", "club for talented students", "community consultation", "reading group", "programme launch", "network event", "recurring event", "event", "function", "soirees", "party", "your business", "symposium", "business coach", "business masterclass", "what's on", "what\u2019s on", "alumni", "visually impaired", "research training", "senior screening", "online marketing", "taster session", "nt encore", "met opera live", "nt live:", "nt live encore", "roh live:", "hire", "summer school", "translation workshop", "jewellery workshop", "vocal workshop", "one-day workshop", "join us for our weekly", "highlights tour", "adult learning", "educational events", "walking tour", "conference programme", "fun palace", "create your own", "m t w t f", "2 3 4 5 6", "careers advice", "memorial service", "speed dating", "ukulele class", "dance class", "yoga class", "yoga practice", "zumba classes", "how to apply", "language class", "fitness class", "open days", "open day", "open evening", "life drawing", "confirmation service", "evening walk", "complete beginners", "champions league final", "birthday bash", "quiz night", "pub quiz", "club night", "half-term", "half term", "end of term", "children's event", "family craft", "family concert", "family events", "parent & baby", "your little ones", "workshop for children", "sessions for children", "young people's", "parents and babies", "parents & babies", "kids & families", "schools workshop", "family fun", "bring the kids", "family film", "families & youth", "0-5 yrs", "2-5yrs", "6mths-5yrs", "2-4 year olds", "2-5 year-olds", "ages 2+", "ages 3+", "ages 4+", "ciné kids", "aged 4-8", "under-11s", "4 kids", "for kids", "kids'", "kids\u2019", "family drop-in", "family workshop", "family weekend", "family activities", "family festival", "london cocktail week", "euros", "euro");
    static final Map<Util.Lang, List<String>> LANGUAGE_EXCLUSIONS = Map.of(Util.Lang.ENG, EXC);
    static final List<String> EXC_CANCELLED = Util.list("cancelled", "canceled", "postponed", "event closed", "registration closed");
    static final List<String> EXC_ONLINE = Util.list("online event", "online talk");
    static final List<String> PHRASES_TO_REMOVE = Util.list("(sold out)", "sold out", "(fully booked)", "fully booked", "concessions", "concession", "upcoming exhibition", "upcoming events", "upcoming event", "view more", "view event details", "view event", "view detail", "event details", "transaction fee", "is proud to present", "plus guests", "+ guests", "and more", "+ more", "plus guests", "an evening with", "album launch party", "cd launch", "album launch", "single launch party", "solo lp launch", " ep launch", "single launch", "single release", "after party", "official afterparty", " and book launch", "book launch", "ebook launch", "launch event", "join the waiting list", "[r18]", "uk premiere", "live in-store", "live in concert", "*venue change*", "venue change", "multiple dates", "view", "book now", "book seats", "meeting point", "wheelchair access", "talks and tours", "talks and lectures", "info and tickets", "find tickets", "buy tickets", "join the guestlist", "promotions", "limited advance", "multi-buy discount", "(map)", " more info", "more info ", "please note", "ticketed event", "limited availability", "live in london", "& special guests", "and special guests", "plus special guests", "+ special guests", "plus support", "clubnight", "time to be announced", "includes a welcome drink", "to be announced soon", "to be announced", "tbc", "show times vary", "extra show added", "upstairs @ ronnie's", " of every month", "live music sessions", "live music session", "to live music", "live music", "live event", "matinée show", "(preview)", "(extended)", "dates:", "(wip)", "(work in progress)", "work in progress", "edinburgh previews", "edfringe preview", "ed previews", "edinburgh preview", "double bill", "2nd date added", "camden fringe", "barclaycard customers", "pre-concert talk", "2019/20", "shubbak festival", "postponed", "canceled", "cancelled", "[postponed]", "[cancelled]", "rescheduled");
    static final List<String> PHRASES_TO_REMOVE_SAFELY = Util.list("adv", "tba", "£");
    static final List<String> SINGLE_PARTS_TO_REMOVE = Util.list("coming up", "now showing", "tickets", "find", "share this", "book an area", "music", "book", "/", "t", "&", "!", ">", "category", "limited places", "students", "waiting list", "and", "to", "and info", "recitals", "per day", "more info", "event info", "dates", "entry", "every", "continue", "more", "now", "lunch", "lunchtime", "registration open", "approx", "the", "concerts", "from", "join us", "for further information", "tell me more", "rsvp", "starts", "date", "no charge", "auditorium", "view", "info book", "hire us", "events", "cash otd", "returns only", "event page", "otd", "london, uk", "change of artist", "@", "doors", "show", "price", "info", "doors", "adv", "door", "meet", "church", "other", "group", "pm", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday", "thur", "sun", "sun,", "featured", "monday,", "tuesday,", "wednesday,", "thursday,", "friday,", "saturday,", "sunday,", "sun", "sun,", "mondays", "tuesdays", "wednesdays", "thursdays", "fridays", "saturdays", "sundays", "start", "end", "start time", "event starts", "location", "get", "with", "late", "doors open", "today", "tomorrow", "learning", "3p", "6p", "7p", "8p", "9p", "10p", "11p", "12p", "30p", "sun 6p", "sun 30p", "sun p", "films", "highlights", "previous", "club", "tbc", "to 1", "to 3", "to 4", "to 5", "to 2", "to 6", "to 7", "to 8", "to 9", "to 10", "to 11", "to 11", "to 13", "to 14", "to 15", "to 12", "to 16", "to 17", "to 18", "to 19", "to 20", "to 21", "to 23", "to 24", "to 25", "to 22", "to 26", "to 27", "to 28", "to 29", "to 30", "to 31", "postponed", "cancelled", "[postponed]", "[cancelled]");
    static final List<String> PHRASES_TO_CLEAN_FROM_START_OF_TEXT = Util.list("+", "paid", "&", "performance", "talks", "lectures", "discussions", "talk", "workshop", "workshops", "cinema", "courses", "classes", "events", "gigs", "event", "coming soon", "and", "featured", "event,", "film screening", "innervisions", "shubbak");
    static final ArrayList<String> START_PARTS_TO_REMOVE = Util.list("comedy", "dance", "theatre", "exhibition", "music", "family", "sport", "meeting", "and", "lecture", "seminar", "external", "drama", "workshop", "festival", "t", "Sun");
    static final List<String> REMOVE_FROM_ENDS_OF_PARTS = Util.list("the", "with", "share this");
    static final List<String> REMOVE_FROM_ENDS_OF_PARTS_LONG = Util.list("live");
    static final List<String> SOLDOUT_INDICATORS = Util.list("sold out", "fully booked", "ausverkauft");
    static final List<String> EXC_FIRST_3 = Util.list("members", "closed", "closure", "brunch", "bsl", "course:", "dj");
    static final List<String> EXC_FIRST_6_PHRASE = Util.list("audio description", "backstage tours");
    static final List<String> EXC_FIRST_6 = Util.list("workshop", "workshop:", "workshops", "teachers'", "teachers\u2019", "\u00AE");
    static final List<String> EXC_WEBINAR = Util.list("webinar");
    static final List<String> EXC_FIRST_6_CHURCH = Util.list("communion");
    static final ArrayList<String> EXC_START = Util.list("guided tour", "book group", "art course", "round table", "fitness", "career", "interview skills", "wedding", "membership", "opening hours", "opening times", "architecture tour", "life drawing");
    static final List<String> EXC_PARTS = Util.list("family", "course", "no recital", "workshop", "student night", "party");
    static final Util.MultiList<String, String> PAIR_EXC = constructDoubleExclusions();

    static Util.MultiList<String, String> constructDoubleExclusions() {
        Util.MultiList<String, String> m = new Util.MultiList<>();
        m.underlying = Util.list(new Util.Multi<>("kids", "families"), new Util.Multi<>("postgraduate", "seminar"));
        return m;
    }
}